//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var Breeders = newBreedersTable("BabyPetControl", "Breeders", "")

type breedersTable struct {
	mysql.Table

	// Columns
	ID    mysql.ColumnInteger
	Name  mysql.ColumnString
	Color mysql.ColumnString
	Age   mysql.ColumnDate

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type BreedersTable struct {
	breedersTable

	NEW breedersTable
}

// AS creates new BreedersTable with assigned alias
func (a BreedersTable) AS(alias string) *BreedersTable {
	return newBreedersTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new BreedersTable with assigned schema name
func (a BreedersTable) FromSchema(schemaName string) *BreedersTable {
	return newBreedersTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new BreedersTable with assigned table prefix
func (a BreedersTable) WithPrefix(prefix string) *BreedersTable {
	return newBreedersTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new BreedersTable with assigned table suffix
func (a BreedersTable) WithSuffix(suffix string) *BreedersTable {
	return newBreedersTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newBreedersTable(schemaName, tableName, alias string) *BreedersTable {
	return &BreedersTable{
		breedersTable: newBreedersTableImpl(schemaName, tableName, alias),
		NEW:           newBreedersTableImpl("", "new", ""),
	}
}

func newBreedersTableImpl(schemaName, tableName, alias string) breedersTable {
	var (
		IDColumn       = mysql.IntegerColumn("Id")
		NameColumn     = mysql.StringColumn("Name")
		ColorColumn    = mysql.StringColumn("Color")
		AgeColumn      = mysql.DateColumn("Age")
		allColumns     = mysql.ColumnList{IDColumn, NameColumn, ColorColumn, AgeColumn}
		mutableColumns = mysql.ColumnList{NameColumn, ColorColumn, AgeColumn}
	)

	return breedersTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:    IDColumn,
		Name:  NameColumn,
		Color: ColorColumn,
		Age:   AgeColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
