//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var Matrices = newMatricesTable("BabyPetControl", "Matrices", "")

type matricesTable struct {
	mysql.Table

	// Columns
	ID    mysql.ColumnInteger
	Name  mysql.ColumnString
	Color mysql.ColumnString
	Age   mysql.ColumnDate

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type MatricesTable struct {
	matricesTable

	NEW matricesTable
}

// AS creates new MatricesTable with assigned alias
func (a MatricesTable) AS(alias string) *MatricesTable {
	return newMatricesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new MatricesTable with assigned schema name
func (a MatricesTable) FromSchema(schemaName string) *MatricesTable {
	return newMatricesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new MatricesTable with assigned table prefix
func (a MatricesTable) WithPrefix(prefix string) *MatricesTable {
	return newMatricesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new MatricesTable with assigned table suffix
func (a MatricesTable) WithSuffix(suffix string) *MatricesTable {
	return newMatricesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newMatricesTable(schemaName, tableName, alias string) *MatricesTable {
	return &MatricesTable{
		matricesTable: newMatricesTableImpl(schemaName, tableName, alias),
		NEW:           newMatricesTableImpl("", "new", ""),
	}
}

func newMatricesTableImpl(schemaName, tableName, alias string) matricesTable {
	var (
		IDColumn       = mysql.IntegerColumn("Id")
		NameColumn     = mysql.StringColumn("Name")
		ColorColumn    = mysql.StringColumn("Color")
		AgeColumn      = mysql.DateColumn("Age")
		allColumns     = mysql.ColumnList{IDColumn, NameColumn, ColorColumn, AgeColumn}
		mutableColumns = mysql.ColumnList{NameColumn, ColorColumn, AgeColumn}
	)

	return matricesTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:    IDColumn,
		Name:  NameColumn,
		Color: ColorColumn,
		Age:   AgeColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
